apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: json-to-xml
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
          - methods:
              - POST
            prefix: /json-to-xml
        routeAction:
          single:
            upstream:
              name: default-petstore-8080
              namespace: gloo-system
        options:
          prefixRewrite: /api/pets
          transformations:
            requestTransformation:
              transformationTemplate:
                headers:
                  "body-text":
                    text: >-
                      <soapenv:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:date="http://exslt.org/dates-and-times" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.qas.com/web-2013-12">
                      <soapenv:Header/>
                      <soapenv:Body>
                      <web:QASearch>
                      <web:Country>{{address_request.address_request_fields.alpha_country_code}}</web:Country>
                      <web:Engine Flatten="true" Timeout="1000">Verification</web:Engine>
                      <web:Layout>RegB layout</web:Layout>
                      <web:Search>
                      {{address_request.address_request_fields.line1_text}}
                      {{address_request.address_request_fields.line2_text}}
                      {{address_request.address_request_fields.line3_text}}
                      {{address_request.address_request_fields.line4_text}}
                      {{address_request.address_request_fields.city_text}}
                      {{address_request.address_request_fields.region_area_cd}}
                      {{address_request.address_request_fields.postal_code}}
                      {{address_request.address_request_fields.alpha_country_code}}
                      </web:Search>
                      </web:QASearch>
                      </soapenv:Body>
                      </soapenv:Envelope>
